services:
  leader:
    build: . 
    command: ["gocache", "--role", "leader", "--port", "7000"]
    ports:
      - "7000:7000"
      - "9090:9090"
    volumes:
      - leader-data:/data

  follower1:
    build: .
    command: ["gocache", "--role", "follower", "--port", "7001", "--leader-addr", "leader:8000"]
    ports:
      - "7001:7001"
    depends_on:
      - leader
    volumes:
      - follower1-data:/data
      

  follower2:
    build: .
    command: ["gocache", "--role", "follower", "--port", "7002", "--leader-addr", "leader:8000"]
    ports:
      - "7002:7002"
    depends_on:
      - leader
    volumes:
      - follower2-data:/data

volumes:
  leader-data:
  follower1-data:
  follower2-data: